# Stage 1: Build Angular Application
FROM node:18.10 AS builder

#PROXY

ENV HTTP_PROXY=http://proxy:3128
ENV HTTPS_PROXY=http://proxy:3128


WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli@15.2.4

RUN npm install

COPY . .

# Build the Angular app for production
RUN ng build 

# Stage 2: Serve the Angular Application using Nginx
FROM nginx:1.21


# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built Angular app from the previous stage to Nginx
COPY --from=builder /app/dist/front-monitoring /usr/share/nginx/html



EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
